kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: demo-ns
bases:
  - ../base
patchesStrategicMerge:
  - deployment.yml
images:
  - name: demo-app-image
    newTag: "1.0.0"
    newName: localhost:5000/demo-app
resources:
  - namespace.yml
  - config.yml
  - nodeport-svc.yml