kind: Service
apiVersion: v1
metadata:
  name: nodeport-demo-app
spec:
  type: NodePort
  selector:
    app: demo-app
    type: backend
  ports:
    - name: nodeport-demo-app-nginx
      protocol: TCP
      port: 80
      nodePort: 32000
    - name: nodeport-demo-app-debug
      protocol: TCP
      port: 8787
      nodePort: 32001