version: '3.8'
services:
  nginx: 
    image: nginx:latest
    container_name: my-web-server
    volumes:
      - ./nginx-files/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-files/40x.html:/usr/share/nginx/html/40x.html
    ports:
      - 8080:80